import {IClassService} from "../service/class/i-class-service";
import {ICallExpressionService} from "../service/call-expression/i-call-expression-service";
import {IConstructorService} from "../service/constructor/i-constructor-service";
import {IDecoratorService} from "../service/decorator/i-decorator-service";
import {IExportService} from "../service/export/i-export-service";
import {IHeritageClauseService} from "../service/heritage-clause/i-heritage-clause-service";
import {IImportService} from "../service/import/i-import-service";
import {IInterfaceDeclarationService} from "../service/interface-declaration/i-interface-declaration-service";
import {IMethodService} from "../service/method/i-method-service";
import {IModifierService} from "../service/modifier/i-modifier-service";
import {INamedExportsService} from "../service/named-exports/i-named-exports-service";
import {INamedImportsService} from "../service/named-imports/i-named-imports-service";
import {INamespaceImportService} from "../service/namespace-import/i-namespace-import-service";
import {IParameterService} from "../service/parameter/i-parameter-service";
import {IPropertyService} from "../service/property/i-property-service";
import {ITypeLiteralNodeService} from "../service/type-literal-node/i-type-literal-node-service";
import {ITypescriptLanguageService} from "@wessberg/typescript-language-service";
import {IPropertyAccessExpressionService} from "../service/property-access-expression/i-property-access-expression-service";
import {IResolver} from "../resolver/i-resolver-getter";
import {IPrinter} from "@wessberg/typescript-ast-util";
import {ITypeElementService} from "../service/type-element/i-type-element-service";
import {ITypeNodeService} from "../service/type-node/i-type-node-service";
import {IPropertyNameService} from "../service/property-name/i-property-name-service";
import {IPropertySignatureService} from "../service/property-signature/i-property-signature-service";
import {IMethodSignatureService} from "../service/method-signature/i-method-signature-service";
import {IIndexSignatureService} from "../service/index-signature/i-index-signature-service";
import {IBindingElementService} from "../service/binding-element/i-binding-element-service";
import {IRegularExpressionLiteralService} from "../service/regular-expression-literal/i-regular-expression-literal-service";
import {IStringLiteralService} from "../service/string-literal/i-string-literal-service";
import {INumericLiteralService} from "../service/numeric-literal/i-numeric-literal-service";
import {INoSubstitutionTemplateLiteralService} from "../service/no-substitution-template-literal/i-no-substitution-template-literal-service";
import {IIdentifierService} from "../service/identifier/i-identifier-service";
import {IComputedPropertyNameService} from "../service/computed-property-name/i-computed-property-name-service";
import {IBindingNameService} from "../service/binding-name/i-binding-name-service";
import {IBindingPatternService} from "../service/binding-pattern/i-binding-pattern-service";
import {ISetAccessorService} from "../service/set-accessor/i-set-accessor-service";
import {IGetAccessorService} from "../service/get-accessor/i-get-accessor-service";
import {IParser} from "../parser/i-parser";
import {ITemplateExpressionService} from "../service/template-expression/i-template-expression-service";

export interface ICodeAnalyzerBase {
	readonly languageService: ITypescriptLanguageService;
	readonly classService: IClassService;
	readonly resolver: IResolver;
	readonly printer: IPrinter;
	readonly parser: IParser;
	readonly callExpressionService: ICallExpressionService;
	readonly propertyAccessExpressionService: IPropertyAccessExpressionService;
	readonly constructorService: IConstructorService;
	readonly decoratorService: IDecoratorService;
	readonly exportService: IExportService;
	readonly heritageClauseService: IHeritageClauseService;
	readonly importService: IImportService;
	readonly interfaceDeclarationService: IInterfaceDeclarationService;
	readonly methodService: IMethodService;
	readonly modifierService: IModifierService;
	readonly namedExportsService: INamedExportsService;
	readonly namedImportsService: INamedImportsService;
	readonly namespaceImportService: INamespaceImportService;
	readonly parameterService: IParameterService;
	readonly propertyService: IPropertyService;
	readonly typeLiteralNodeService: ITypeLiteralNodeService;
	readonly typeElementService: ITypeElementService;
	readonly typeNodeService: ITypeNodeService;
	readonly propertyNameService: IPropertyNameService;
	readonly propertySignatureService: IPropertySignatureService;
	readonly methodSignatureService: IMethodSignatureService;
	readonly indexSignatureService: IIndexSignatureService;
	readonly bindingElementService: IBindingElementService;
	readonly identifierService: IIdentifierService;
	readonly stringLiteralService: IStringLiteralService;
	readonly numericLiteralService: INumericLiteralService;
	readonly noSubstitutionTemplateLiteralService: INoSubstitutionTemplateLiteralService;
	readonly regularExpressionLiteralService: IRegularExpressionLiteralService;
	readonly computedPropertyNameService: IComputedPropertyNameService;
	readonly bindingNameService: IBindingNameService;
	readonly bindingPatternService: IBindingPatternService;
	readonly getAccessorService: IGetAccessorService;
	readonly setAccessorService: ISetAccessorService;
	readonly templateExpressionService: ITemplateExpressionService;
}
