import {AccessorDeclaration, ArrayBindingElement, ArrayBindingPattern, BindingElement, BindingName, CallSignatureDeclaration, ClassDeclaration, ClassElement, ClassExpression, ConstructorDeclaration, ConstructSignatureDeclaration, Decorator, ExportSpecifier, FunctionLikeDeclaration, GetAccessorDeclaration, HeritageClause, Identifier, ImportClause, ImportSpecifier, IndexSignatureDeclaration, InterfaceDeclaration, MethodDeclaration, MethodSignature, ModifiersArray, ObjectBindingPattern, ParameterDeclaration, PropertyDeclaration, PropertySignature, SetAccessorDeclaration, SignatureDeclaration, TypeElement, TypeLiteralNode} from "typescript";
import {IClassDict} from "../light-ast/dict/class/i-class-dict";
import {IImportClauseDict} from "../light-ast/dict/import-clause/i-import-clause-dict";
import {INamedImportExportDict} from "../light-ast/dict/named-import-export/i-named-import-export-dict";
import {ITypeLiteralDict} from "../light-ast/dict/type-literal/i-type-literal-dict";
import {ITypeElementDict, TypeElementDict} from "../light-ast/dict/type-element/i-type-element-dict";
import {HeritageDict, IExtendsHeritageDict, IImplementsHeritageDict} from "../light-ast/dict/heritage/i-heritage-dict";
import {IAllModifiersDict} from "../light-ast/dict/modifier/i-all-modifiers-dict";
import {IPropertySignatureDict} from "../light-ast/dict/property-signature/i-property-signature-dict";
import {ICallSignatureDict} from "../light-ast/dict/call-signature/i-call-signature-dict";
import {IConstructSignatureDict} from "../light-ast/dict/construct-signature/i-construct-signature-dict";
import {IMethodSignatureDict} from "../light-ast/dict/method-signature/i-method-signature-dict";
import {IIndexSignatureDict} from "../light-ast/dict/index-signature/i-index-signature-dict";
import {ISignatureDict} from "../light-ast/dict/signature/i-signature-dict";
import {IParameterDict} from "../light-ast/dict/parameter/i-parameter-dict";
import {BindingNameDict, IArrayBindingNameDict, INormalBindingNameDict, IObjectBindingNameDict} from "../light-ast/dict/binding-name/binding-name-dict";
import {ArrayBindingElementDict, INormalArrayBindingElementDict, IOmittedArrayBindingElementDict} from "../light-ast/dict/binding-element/array-binding-element-dict";
import {IDecoratorDict} from "../light-ast/dict/decorator/i-decorator-dict";
import {ClassAccessorDict} from "../light-ast/dict/class-accessor/class-accessor-dict";
import {AccessorDict, IAccessorDict, IGetAccessorDict, ISetAccessorDict} from "../light-ast/dict/accessor/accessor-dict";
import {IFunctionLikeDict} from "../light-ast/dict/function-like/i-function-like-dict";
import {IClassPropertyDict} from "../light-ast/dict/class-property/i-class-property-dict";
import {IClassMethodDict} from "../light-ast/dict/class-method/i-class-method-dict";
import {IMethodDict} from "../light-ast/dict/method/i-method-dict";
import {IFunctionLikeWithParametersDict} from "../light-ast/dict/function-like-with-parameters/i-function-like-with-parameters-dict";
import {ClassElementDict} from "../light-ast/dict/class-element/class-element-dict";
import {IObjectBindingElementDict} from "../light-ast/dict/binding-element/i-object-binding-element-dict";
import {IInterfaceDict} from "../light-ast/dict/interface/i-interface-dict";
import {IConstructorDict} from "../light-ast/dict/constructor/i-constructor-dict";
import {INodeToCtorMapperBase} from "../node-to-ctor-mapper/i-node-to-ctor-mapper";
import {Optional} from "../optional/optional";

export interface INodeToDictMapperBase extends INodeToCtorMapperBase {
	toIClassDict (node: Optional<ClassDeclaration|ClassExpression>): IClassDict|null;
	toIImportClauseDict (node: Optional<ImportClause>): IImportClauseDict|null;
	toINamedImportExportDict (node: Optional<ImportSpecifier|ExportSpecifier>): INamedImportExportDict|null;
	toITypeLiteralDict (node: Optional<TypeLiteralNode|InterfaceDeclaration>): ITypeLiteralDict|null;
	toIInterfaceDict (node: Optional<InterfaceDeclaration>): IInterfaceDict|null;
	toITypeElementDict (node: Optional<TypeElement>): ITypeElementDict|null;
	toTypeElementDict (node: Optional<TypeElement>): TypeElementDict|null;
	toHeritageDict (node: Optional<HeritageClause>): HeritageDict|null;
	toIAllModifiersDict (modifiers: Optional<ModifiersArray>): IAllModifiersDict|null;
	toIExtendsHeritageDict (node: Optional<HeritageClause>): IExtendsHeritageDict|null;
	toIImplementsHeritageDict (node: Optional<HeritageClause>): IImplementsHeritageDict|null;
	toIPropertySignatureDict (node: Optional<PropertySignature>): IPropertySignatureDict|null;
	toICallSignatureDict (node: Optional<CallSignatureDeclaration>): ICallSignatureDict|null;
	toIConstructSignatureDict (node: Optional<ConstructSignatureDeclaration>): IConstructSignatureDict|null;
	toIMethodSignatureDict (node: Optional<MethodSignature>): IMethodSignatureDict|null;
	toIIndexSignatureDict (node: Optional<IndexSignatureDeclaration>): IIndexSignatureDict|null;
	toISignatureDict (node: Optional<SignatureDeclaration>): ISignatureDict|null;
	toIParameterDict (node: Optional<ParameterDeclaration>): IParameterDict|null;
	toBindingNameDict (node: Optional<BindingName>): BindingNameDict|null;
	toINormalBindingNameDict (node: Optional<Identifier>): INormalBindingNameDict|null;
	toIObjectBindingNameDict (node: Optional<ObjectBindingPattern>): IObjectBindingNameDict|null;
	toIArrayBindingNameDict (node: Optional<ArrayBindingPattern>): IArrayBindingNameDict|null;
	toIObjectBindingElementDict (node: Optional<BindingElement>): IObjectBindingElementDict|null;
	toINormalArrayBindingElementDict (node: Optional<BindingElement>): INormalArrayBindingElementDict|null;
	toIOmittedArrayBindingElementDict (node: Optional<ArrayBindingElement>): IOmittedArrayBindingElementDict|null;
	toArrayBindingElementDict (node: Optional<ArrayBindingElement>): ArrayBindingElementDict|null;
	toIDecoratorDict (node: Optional<Decorator>): IDecoratorDict|null;
	toClassElementDict (node: Optional<ClassElement>): ClassElementDict|null;
	toClassAccessorDict (node: Optional<AccessorDeclaration>): ClassAccessorDict|null;
	toAccessorDict (node: Optional<AccessorDeclaration>): AccessorDict|null;
	toIFunctionLikeDict (node: Optional<FunctionLikeDeclaration>): IFunctionLikeDict|null;
	toIGetAccessorDict (node: Optional<GetAccessorDeclaration>): IGetAccessorDict|null;
	toISetAccessorDict (node: Optional<SetAccessorDeclaration>): ISetAccessorDict|null;
	toIAccessorDict (node: Optional<AccessorDeclaration>): IAccessorDict|null;
	toIClassPropertyDict (node: Optional<PropertyDeclaration>): IClassPropertyDict|null;
	toIClassMethodDict (node: Optional<MethodDeclaration>): IClassMethodDict|null;
	toIMethodDict (node: Optional<MethodDeclaration>): IMethodDict|null;
	toIFunctionLikeWithParametersDict (node: Optional<FunctionLikeDeclaration>): IFunctionLikeWithParametersDict|null;
	toIConstructorDict (node: Optional<ConstructorDeclaration>): IConstructorDict|null;
}