import {ArrayBindingElement, ArrayBindingPattern, BindingElement, BindingName, CallSignatureDeclaration, ConstructSignatureDeclaration, Decorator, ExportSpecifier, HeritageClause, Identifier, ImportClause, ImportSpecifier, IndexSignatureDeclaration, InterfaceDeclaration, MethodSignature, ObjectBindingPattern, ParameterDeclaration, PropertySignature, SignatureDeclaration, TypeElement, TypeLiteralNode} from "typescript";
import {IImportClauseDict} from "../light-ast/dict/import-clause/i-import-clause-dict";
import {INamedImportExportDict} from "../light-ast/dict/named-import-export/i-named-import-export-dict";
import {ITypeLiteralDict} from "../light-ast/dict/type-literal/i-type-literal-dict";
import {IInterfaceDict} from "../light-ast/dict/interface/i-interface-dict";
import {ITypeElementDict, TypeElementDict} from "../light-ast/dict/type-element/i-type-element-dict";
import {HeritageDict, IExtendsHeritageDict, IImplementsHeritageDict} from "../light-ast/dict/heritage/i-heritage-dict";
import {IPropertySignatureDict} from "../light-ast/dict/property-signature/i-property-signature-dict";
import {ICallSignatureDict} from "../light-ast/dict/call-signature/i-call-signature-dict";
import {IConstructSignatureDict} from "../light-ast/dict/construct-signature/i-construct-signature-dict";
import {IMethodSignatureDict} from "../light-ast/dict/method-signature/i-method-signature-dict";
import {IIndexSignatureDict} from "../light-ast/dict/index-signature/i-index-signature-dict";
import {ISignatureDict} from "../light-ast/dict/signature/i-signature-dict";
import {IParameterDict} from "../light-ast/dict/parameter/i-parameter-dict";
import {BindingNameDict, IArrayBindingNameDict, INormalBindingNameDict, IObjectBindingNameDict} from "../light-ast/dict/binding-name/binding-name-dict";
import {IObjectBindingElementDict} from "../light-ast/dict/binding-element/i-object-binding-element-dict";
import {ArrayBindingElementDict, INormalArrayBindingElementDict, IOmittedArrayBindingElementDict} from "../light-ast/dict/binding-element/array-binding-element-dict";
import {IDecoratorDict} from "../light-ast/dict/decorator/i-decorator-dict";

export interface INodeToDictMapperBase {
	toIImportClauseDict (node: ImportClause|undefined|null): IImportClauseDict|null;
	toINamedImportExportDict (node: ImportSpecifier|ExportSpecifier|undefined|null): INamedImportExportDict|null;
	toITypeLiteralDict (node: TypeLiteralNode|InterfaceDeclaration|undefined|null): ITypeLiteralDict|null;
	toIInterfaceDict (node: InterfaceDeclaration|undefined|null): IInterfaceDict|null;
	toITypeElementDict (node: TypeElement|undefined|null): ITypeElementDict|null;
	toTypeElementDict (node: TypeElement|undefined|null): TypeElementDict|null;
	toHeritageDict (node: HeritageClause|undefined|null): HeritageDict|null;
	toIExtendsHeritageDict (node: HeritageClause|undefined|null): IExtendsHeritageDict|null;
	toIImplementsHeritageDict (node: HeritageClause|undefined|null): IImplementsHeritageDict|null;
	toIPropertySignatureDict (node: PropertySignature|undefined|null): IPropertySignatureDict|null;
	toICallSignatureDict (node: CallSignatureDeclaration|undefined|null): ICallSignatureDict|null;
	toIConstructSignatureDict (node: ConstructSignatureDeclaration|undefined|null): IConstructSignatureDict|null;
	toIMethodSignatureDict (node: MethodSignature|undefined|null): IMethodSignatureDict|null;
	toIIndexSignatureDict (node: IndexSignatureDeclaration|undefined|null): IIndexSignatureDict|null;
	toISignatureDict (node: SignatureDeclaration|undefined|null): ISignatureDict|null;
	toIParameterDict (node: ParameterDeclaration|undefined|null): IParameterDict|null;
	toBindingNameDict (node: BindingName|undefined|null): BindingNameDict|null;
	toINormalBindingNameDict (node: Identifier|undefined|null): INormalBindingNameDict|null;
	toIObjectBindingNameDict (node: ObjectBindingPattern|undefined|null): IObjectBindingNameDict|null;
	toIArrayBindingNameDict (node: ArrayBindingPattern|undefined|null): IArrayBindingNameDict|null;
	toIObjectBindingElementDict (node: BindingElement|undefined|null): IObjectBindingElementDict|null;
	toINormalArrayBindingElementDict (node: BindingElement|undefined|null): INormalArrayBindingElementDict|null;
	toIOmittedArrayBindingElementDict (node: ArrayBindingElement|undefined|null): IOmittedArrayBindingElementDict|null;
	toArrayBindingElementDict (node: ArrayBindingElement|undefined|null): ArrayBindingElementDict|null;
	toIDecoratorDict (node: Decorator|undefined|null): IDecoratorDict|null;
}