export enum FormattedExpressionKind {
	EXPRESSION = "EXPRESSION",
	CALL_EXPRESSION = "CALL_EXPRESSION",
	ARGUMENTS = "ARGUMENTS",
	STRING_LITERAL = "STRING_LITERAL",
	NUMBER_LITERAL = "NUMBER_LITERAL",
	NOT_IMPLEMENTED = "NOT_IMPLEMENTED",
	PROPERTY_ACCESS = "PROPERTY_ACCESS",
	IDENTIFIER = "IDENTIFIER"
}