import "./services";
// Services
export {CodeAnalyzer} from "./code-analyzer/code-analyzer";
export {ICodeAnalyzer} from "./code-analyzer/i-code-analyzer";
export {IClassService} from "./service/class/i-class-service";
export {ICallExpressionService} from "./service/call-expression/i-call-expression-service";
export {IPropertyAccessExpressionService} from "./service/property-access-expression/i-property-access-expression-service";
export {IConstructorService} from "./service/constructor/i-constructor-service";
export {IDecoratorService} from "./service/decorator/i-decorator-service";
export {IExportService} from "./service/export/i-export-service";
export {IHeritageClauseService} from "./service/heritage-clause/i-heritage-clause-service";
export {IImportService} from "./service/import/i-import-service";
export {IInterfaceDeclarationService} from "./service/interface-declaration/i-interface-declaration-service";
export {IMethodService} from "./service/method/i-method-service";
export {IModifierService} from "./service/modifier/i-modifier-service";
export {INamedExportsService} from "./service/named-exports/i-named-exports-service";
export {INamedImportsService} from "./service/named-imports/i-named-imports-service";
export {INamespaceImportService} from "./service/namespace-import/i-namespace-import-service";
export {IParameterService} from "./service/parameter/i-parameter-service";
export {IPropertyService} from "./service/property/i-property-service";
export {ITypeLiteralNodeService} from "./service/type-literal-node/i-type-literal-node-service";
export {IResolver} from "./resolver/i-resolver-getter";
export {IPrinter} from "@wessberg/typescript-ast-util";

// Dicts
export {ISetAccessorDict, IGetAccessorDict, IAccessorDict, AccessorDict} from "./dict/accessor/accessor-dict";
export {AccessorKind} from "./dict/accessor/accessor-kind";
export {ArrayBindingElementDict, INormalArrayBindingElementDict, IOmittedArrayBindingElementDict} from "./dict/binding-element/array-binding-element-dict";
export {ArrayBindingElementKind} from "./dict/binding-element/array-binding-element-kind";
export {IObjectBindingElementDict} from "./dict/binding-element/i-object-binding-element-dict";
export {BindingNameDict, IObjectBindingNameDict, INormalBindingNameDict, IArrayBindingNameDict, IBindingNameDict} from "./dict/binding-name/binding-name-dict";
export {BindingNameKind} from "./dict/binding-name/binding-name-kind";
export {IClassDict} from "./dict/class/i-class-dict";
export {IClassSetAccessorDict, IClassGetAccessorDict, ClassAccessorDict, IClassAccessorDict} from "./dict/class-accessor/class-accessor-dict";
export {ClassElementDict} from "./dict/class-element/class-element-dict";
export {IClassMethodDict} from "./dict/class-method/i-class-method-dict";
export {IClassPropertyDict} from "./dict/class-property/i-class-property-dict";
export {IConstructorDict} from "./dict/constructor/i-constructor-dict";
export {IDecoratorDict, DecoratorDict, IIdentifierDecoratorDict, IExpressionDecoratorDict} from "./dict/decorator/decorator-dict";
export {DecoratorKind} from "./dict/decorator/decorator-kind";
export {IArrowFunctionDict, INormalFunctionDict, IFunctionDict, FunctionDict} from "./dict/function/function-dict";
export {FunctionKind} from "./dict/function/function-kind";
export {IFunctionLikeDict} from "./dict/function-like/i-function-like-dict";
export {IFunctionLikeWithParametersDict} from "./dict/function-like-with-parameters/i-function-like-with-parameters-dict";
export {HeritageKind} from "./dict/heritage/heritage-kind";
export {IImplementsHeritageDict, HeritageDict, IExtendsHeritageDict, IHeritageDict} from "./dict/heritage/i-heritage-clause-dict";
export {IImportDict} from "./dict/import/i-import-dict";
export {IImportClauseDict} from "./dict/import-clause/i-import-clause-dict";
export {IMethodDict} from "./dict/method/i-method-dict";
export {IAllModifiersDict} from "./dict/modifier/i-all-modifiers-dict";
export {ModifierKind} from "./dict/modifier/modifier-kind";
export {INameWithTypeArguments} from "./dict/name-with-type-arguments/i-name-with-type-arguments";
export {INamedImportExportDict} from "./dict/named-import-export/i-named-import-export-dict";
export {INodeDict, PredicateArgument} from "./dict/node/i-node-dict";
export {NodeKind} from "./dict/node/node-kind";
export {IArrayBindingParameterDict, ParameterDict, INormalParameterDict, IObjectBindingParameterDict, IParameterDict} from "./dict/parameter/parameter-dict";
export {ParameterKind} from "./dict/parameter/parameter-kind";
export {VisibilityKind} from "./dict/visibility/visibility-kind";

// Predicates for dicts
export {isAccessorDict} from "./dict/accessor/is-accessor-dict";
export {isIAccessorDict} from "./dict/accessor/is-i-accessor-dict";
export {isIGetAccessorDict} from "./dict/accessor/is-i-get-accessor-dict";
export {isISetAccessorDict} from "./dict/accessor/is-i-set-accessor-dict";
export {isArrayBindingElementDict} from "./dict/binding-element/is-array-binding-element-dict";
export {isINormalArrayBindingElementDict} from "./dict/binding-element/is-i-normal-array-binding-element-dict";
export {isIOmittedArrayBindingElementDict} from "./dict/binding-element/is-i-omitted-array-binding-element-dict";
export {isBindingNameDict} from "./dict/binding-name/is-binding-name-dict";
export {isIArrayBindingNameDict} from "./dict/binding-name/is-i-array-binding-name-dict";
export {isIBindingNameDict} from "./dict/binding-name/is-i-binding-name-dict";
export {isINormalBindingNameDict} from "./dict/binding-name/is-i-normal-binding-name-dict";
export {isIObjectBindingNameDict} from "./dict/binding-name/is-i-object-binding-name-dict";
export {isIClassDict} from "./dict/class/is-i-class-dict";
export {isClassAccessorDict} from "./dict/class-accessor/is-class-accessor-dict";
export {isIClassAccessorDict} from "./dict/class-accessor/is-i-class-accessor-dict";
export {isIClassGetAccessorDict} from "./dict/class-accessor/is-i-class-get-accessor-dict";
export {isIClassSetAccessorDict} from "./dict/class-accessor/is-i-class-set-accessor-dict";
export {isClassElementDict} from "./dict/class-element/is-class-element-dict";
export {isIClassMethodDict} from "./dict/class-method/is-i-class-method-dict";
export {isIClassPropertyDict} from "./dict/class-property/is-i-class-property-dict";
export {isIConstructorDict} from "./dict/constructor/is-i-constructor-dict";
export {isDecoratorDict} from "./dict/decorator/is-decorator-dict";
export {isIDecoratorDict} from "./dict/decorator/is-i-decorator-dict";
export {isIExpressionDecoratorDict} from "./dict/decorator/is-i-expression-decorator-dict";
export {isIIdentifierDecoratorDict} from "./dict/decorator/is-i-identifier-decorator-dict";
export {isFunctionDict} from "./dict/function/is-function-dict";
export {isIArrowFunctionDict} from "./dict/function/is-i-arrow-function-dict";
export {isIFunctionDict} from "./dict/function/is-i-function-dict";
export {isINormalFunctionDict} from "./dict/function/is-i-normal-function-dict";
export {isIFunctionLikeDict} from "./dict/function-like/is-i-function-like-dict";
export {isIFunctionLikeWithParametersDict} from "./dict/function-like-with-parameters/is-i-function-like-with-parameters-dict";
export {isHeritageDict} from "./dict/heritage/is-heritage-dict";
export {isIExtendsHeritageDict} from "./dict/heritage/is-i-extends-heritage-dict";
export {isIHeritageDict} from "./dict/heritage/is-i-heritage-dict";
export {isIImplementsHeritageDict} from "./dict/heritage/is-i-implements-heritage-dict";
export {isIImportDict} from "./dict/import/is-i-import-dict";
export {isIImportClauseDict} from "./dict/import-clause/is-i-import-clause-dict";
export {isIMethodDict} from "./dict/method/is-i-method-dict";
export {isINameWithTypeArguments} from "./dict/name-with-type-arguments/is-i-name-with-type-arguments";
export {isINamedImportExportDict} from "./dict/named-import-export/is-i-named-import-export-dict";
export {isIArrayBindingParameterDict} from "./dict/parameter/is-i-array-binding-parameter-dict";
export {isINormalParameterDict} from "./dict/parameter/is-i-normal-parameter-dict";
export {isIObjectBindingParameterDict} from "./dict/parameter/is-i-object-binding-parameter-dict";
export {isIParameterDict} from "./dict/parameter/is-i-parameter-dict";
export {isParameterDict} from "./dict/parameter/is-parameter-dict";

// Types
export {PropertyAccessCallExpression} from "./service/call-expression/property-access-call-expression";