import {IMarshaller, Marshaller} from "@wessberg/marshaller";
import {ITypeDetector, TypeDetector} from "@wessberg/typedetector";
import {FileLoader, IFileLoader} from "@wessberg/fileloader";
import {IIdentifierUtil} from "./util/interface/IIdentifierUtil";
import {IdentifierUtil} from "./util/IdentifierUtil";
import {ITypeUtil} from "./util/interface/ITypeUtil";
import {TypeUtil} from "./util/TypeUtil";
import {ITokenSerializer} from "./serializer/interface/ITokenSerializer";
import {TokenSerializer} from "./serializer/TokenSerializer";
import {ITokenPredicator} from "./predicate/interface/ITokenPredicator";
import {TokenPredicator} from "./predicate/TokenPredicator";
import {IStringUtil} from "./util/interface/IStringUtil";
import {StringUtil} from "./util/StringUtil";
import {INameGetter} from "./getter/interface/INameGetter";
import {NameGetter} from "./getter/NameGetter";
import {ISourceFilePropertiesGetter} from "./getter/interface/ISourceFilePropertiesGetter";
import {SourceFilePropertiesGetter} from "./getter/SourceFilePropertiesGetter";
import {ITypeExpressionGetter} from "./getter/interface/ITypeExpressionGetter";
import {TypeExpressionGetter} from "./getter/TypeExpressionGetter";
import {IMapper} from "./mapper/interface/IMapper";
import {Mapper} from "./mapper/Mapper";
import {IValueExpressionGetter} from "./getter/interface/IValueExpressionGetter";
import {ValueExpressionGetter} from "./getter/ValueExpressionGetter";
import {ICache} from "./cache/interface/ICache";
import {ITracer} from "./tracer/interface/ITracer";
import {Tracer} from "./tracer/Tracer";
import {IHeritageClauseFormatter} from "./formatter/interface/IHeritageClauseFormatter";
import {HeritageClauseFormatter} from "./formatter/HeritageClauseFormatter";
import {IValueResolvedGetter} from "./getter/interface/IValueResolvedGetter";
import {ValueResolvedGetter} from "./getter/ValueResolvedGetter";
import {IValueableFormatter} from "./formatter/interface/IValueableFormatter";
import {ValueableFormatter} from "./formatter/ValueableFormatter";
import {IModifiersFormatter} from "./formatter/interface/IModifiersFormatter";
import {ModifiersFormatter} from "./formatter/ModifiersFormatter";
import {IVariableFormatter} from "./formatter/interface/IVariableFormatter";
import {VariableFormatter} from "./formatter/VariableFormatter";
import {IDecoratorsFormatter} from "./formatter/interface/IDecoratorsFormatter";
import {DecoratorsFormatter} from "./formatter/DecoratorsFormatter";
import {IPropFormatter} from "./formatter/interface/IPropFormatter";
import {PropFormatter} from "./formatter/PropFormatter";
import {IMutationFormatter} from "./formatter/interface/IMutationFormatter";
import {MutationFormatter} from "./formatter/MutationFormatter";
import {IParametersFormatter} from "./formatter/interface/IParametersFormatter";
import {ParametersFormatter} from "./formatter/ParametersFormatter";
import {IArgumentsFormatter} from "./formatter/interface/IArgumentsFormatter";
import {ArgumentsFormatter} from "./formatter/ArgumentsFormatter";
import {IMethodFormatter} from "./formatter/interface/IMethodFormatter";
import {MethodFormatter} from "./formatter/MethodFormatter";
import {IGetAccessorFormatter} from "./formatter/interface/IGetAccessorFormatter";
import {GetAccessorFormatter} from "./formatter/GetAccessorFormatter";
import {SetAccessorFormatter} from "./formatter/SetAccessorFormatter";
import {ISetAccessorFormatter} from "./formatter/interface/ISetAccessorFormatter";
import {IConstructorFormatter} from "./formatter/interface/IConstructorFormatter";
import {ConstructorFormatter} from "./formatter/ConstructorFormatter";
import {IFunctionFormatter} from "./formatter/interface/IFunctionFormatter";
import {FunctionFormatter} from "./formatter/FunctionFormatter";
import {IArrowFunctionFormatter} from "./formatter/interface/IArrowFunctionFormatter";
import {ArrowFunctionFormatter} from "./formatter/ArrowFunctionFormatter";
import {IClassFormatter} from "./formatter/interface/IClassFormatter";
import {ClassFormatter} from "./formatter/ClassFormatter";
import {ICallExpressionFormatter} from "./formatter/interface/ICallExpressionFormatter";
import {CallExpressionFormatter} from "./formatter/CallExpressionFormatter";
import {IRequireFormatter} from "./formatter/interface/IRequireFormatter";
import {RequireFormatter} from "./formatter/RequireFormatter";
import {INewExpressionFormatter} from "./formatter/interface/INewExpressionFormatter";
import {NewExpressionFormatter} from "./formatter/NewExpressionFormatter";
import {IEnumFormatter} from "./formatter/interface/IEnumFormatter";
import {EnumFormatter} from "./formatter/EnumFormatter";
import {IImportFormatter} from "./formatter/interface/IImportFormatter";
import {ImportFormatter} from "./formatter/ImportFormatter";
import {IExportFormatter} from "./formatter/interface/IExportFormatter";
import {ExportFormatter} from "./formatter/ExportFormatter";
import {Cache} from "./cache/Cache";
import {ILanguageService} from "./service/interface/ILanguageService";
import {LanguageService} from "./service/LanguageService";
import {IStatementUtil} from "./util/interface/IStatementUtil";
import {StatementUtil} from "./util/StatementUtil";
import {IChildStatementGetter} from "./getter/interface/IChildStatementGetter";
import {ChildStatementGetter} from "./getter/ChildStatementGetter";
import {IExportDeclarationGetter} from "./getter/interface/IExportDeclarationGetter";
import {ExportDeclarationGetter} from "./getter/ExportDeclarationGetter";
import {IClassDeclarationGetter} from "./getter/interface/IClassDeclarationGetter";
import {ClassDeclarationGetter} from "./getter/ClassDeclarationGetter";
import {ICallExpressionGetter} from "./getter/interface/ICallExpressionGetter";
import {CallExpressionGetter} from "./getter/CallExpressionGetter";
import {IMutationGetter} from "./getter/interface/IMutationGetter";
import {MutationGetter} from "./getter/MutationGetter";
import {INewExpressionGetter} from "./getter/interface/INewExpressionGetter";
import {NewExpressionGetter} from "./getter/NewExpressionGetter";
import {IFunctionDeclarationGetter} from "./getter/interface/IFunctionDeclarationGetter";
import {FunctionDeclarationGetter} from "./getter/FunctionDeclarationGetter";
import {IEnumDeclarationGetter} from "./getter/interface/IEnumDeclarationGetter";
import {EnumDeclarationGetter} from "./getter/EnumDeclarationGetter";
import {IVariableDeclarationGetter} from "./getter/interface/IVariableDeclarationGetter";
import {VariableDeclarationGetter} from "./getter/VariableDeclarationGetter";
import {IArrowFunctionGetter} from "./getter/interface/IArrowFunctionGetter";
import {ArrowFunctionGetter} from "./getter/ArrowFunctionGetter";
import {IImportDeclarationGetter} from "./getter/interface/IImportDeclarationGetter";
import {ImportDeclarationGetter} from "./getter/ImportDeclarationGetter";
import {IResolvedIdentifierValueGetter} from "./getter/interface/IResolvedIdentifierValueGetter";
import {ResolvedIdentifierValueGetter} from "./getter/ResolvedIdentifierValueGetter";
import {IResolvedSerializedIdentifierValueGetter} from "./getter/interface/IResolvedSerializedIdentifierValueGetter";
import {ResolvedSerializedIdentifierValueGetter} from "./getter/ResolvedSerializedIdentifierValueGetter";
import {IAllIdentifiersGetter} from "./getter/interface/IAllIdentifiersGetter";
import {AllIdentifiersGetter} from "./getter/AllIdentifiersGetter";
import {IPathValidator, PathValidator} from "@wessberg/compiler-common";
import {IFilePathUtil} from "./util/interface/IFilePathUtil";
import {FilePathUtil} from "./util/FilePathUtil";

export const languageService: ILanguageService = new LanguageService();
export const childStatementGetter: IChildStatementGetter = new ChildStatementGetter();
export const importDeclarationGetter: IImportDeclarationGetter = new ImportDeclarationGetter();
export const exportDeclarationGetter: IExportDeclarationGetter = new ExportDeclarationGetter();
export const classDeclarationGetter: IClassDeclarationGetter = new ClassDeclarationGetter();
export const callExpressionGetter: ICallExpressionGetter = new CallExpressionGetter();
export const mutationGetter: IMutationGetter = new MutationGetter();
export const newExpressionGetter: INewExpressionGetter = new NewExpressionGetter();
export const functionDeclarationGetter: IFunctionDeclarationGetter = new FunctionDeclarationGetter();
export const enumDeclarationGetter: IEnumDeclarationGetter = new EnumDeclarationGetter();
export const variableDeclarationGetter: IVariableDeclarationGetter = new VariableDeclarationGetter();
export const arrowFunctionGetter: IArrowFunctionGetter = new ArrowFunctionGetter();
export const resolvedIdentifierValueGetter: IResolvedIdentifierValueGetter = new ResolvedIdentifierValueGetter();
export const resolvedSerializedIdentifierValueGetter: IResolvedSerializedIdentifierValueGetter = new ResolvedSerializedIdentifierValueGetter();
export const allIdentifiersGetter: IAllIdentifiersGetter = new AllIdentifiersGetter();
export const typeDetector: ITypeDetector = new TypeDetector();
export const marshaller: IMarshaller = new Marshaller(typeDetector);
export const fileLoader: IFileLoader = new FileLoader();
export const pathValidatorUtil: IPathValidator = new PathValidator();
export const statementUtil: IStatementUtil = new StatementUtil();
export const identifierUtil: IIdentifierUtil = new IdentifierUtil();
export const typeUtil: ITypeUtil = new TypeUtil();
export const filePathUtil: IFilePathUtil = new FilePathUtil();
export const tokenSerializer: ITokenSerializer = new TokenSerializer();
export const tokenPredicator: ITokenPredicator = new TokenPredicator();
export const stringUtil: IStringUtil = new StringUtil();
export const nameGetter: INameGetter = new NameGetter();
export const sourceFilePropertiesGetter: ISourceFilePropertiesGetter = new SourceFilePropertiesGetter();
export const typeExpressionGetter: ITypeExpressionGetter = new TypeExpressionGetter();
export const mapper: IMapper = new Mapper();
export const cache: ICache = new Cache();
export const tracer: ITracer = new Tracer();
export const heritageClauseFormatter: IHeritageClauseFormatter = new HeritageClauseFormatter();
export const valueExpressionGetter: IValueExpressionGetter = new ValueExpressionGetter();
export const valueResolvedGetter: IValueResolvedGetter = new ValueResolvedGetter();
export const valueableFormatter: IValueableFormatter = new ValueableFormatter();
export const modifiersFormatter: IModifiersFormatter = new ModifiersFormatter();
export const variableFormatter: IVariableFormatter = new VariableFormatter();
export const decoratorsFormatter: IDecoratorsFormatter = new DecoratorsFormatter();
export const propFormatter: IPropFormatter = new PropFormatter();
export const mutationFormatter: IMutationFormatter = new MutationFormatter();
export const parametersFormatter: IParametersFormatter = new ParametersFormatter();
export const argumentsFormatter: IArgumentsFormatter = new ArgumentsFormatter();
export const methodFormatter: IMethodFormatter = new MethodFormatter();
export const getAccessorFormatter: IGetAccessorFormatter = new GetAccessorFormatter();
export const setAccessorFormatter: ISetAccessorFormatter = new SetAccessorFormatter();
export const constructorFormatter: IConstructorFormatter = new ConstructorFormatter();
export const functionFormatter: IFunctionFormatter = new FunctionFormatter();
export const arrowFunctionFormatter: IArrowFunctionFormatter = new ArrowFunctionFormatter();
export const classFormatter: IClassFormatter = new ClassFormatter();
export const callExpressionFormatter: ICallExpressionFormatter = new CallExpressionFormatter();
export const requireFormatter: IRequireFormatter = new RequireFormatter();
export const newExpressionFormatter: INewExpressionFormatter = new NewExpressionFormatter();
export const enumFormatter: IEnumFormatter = new EnumFormatter();
export const importFormatter: IImportFormatter = new ImportFormatter();
export const exportFormatter: IExportFormatter = new ExportFormatter();